# Generated by Django 6.0.7 on 2026-08-08 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0005_alter_notification_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('liked_story', 'Liked Story'), ('liked_comment', 'Liked Comment'), ('commented', 'Commented'), ('replied', 'Replied'), ('new_follower', 'New Follower')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notification_recipient_created_idx'),
        ),
    ]
