# Generated by Django 6.0.7 on 2026-08-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_verb_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='noti_recipient_created_idx',
            old_name='notification_recipient_created_idx',
        ),
    ]
