# Generated by Django 6.0.7 on 2026-08-10 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_rename_notification_recipient_created_idx_noti_recipient_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('liked_story', 'Liked Story'), ('liked_comment', 'Liked Comment'), ('commented', 'Commented'), ('replied', 'Replied'), ('new_follower', 'New Follower'), ('story_published', 'Story Published'), ('account_verified', 'Account Verified'), ('password_changed', 'Password Changed'), ('complete_profile', 'Complete Profile')], max_length=20),
        ),
    ]
