# Generated by Django 6.0.7 on 2026-08-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_actor_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('liked_story', 'Liked Story'), ('liked_comment', 'Liked Comment'), ('commented', 'Commented'), ('replied', 'Replied'), ('new_follower', 'New Follower'), ('complete_profile', 'Complete Profile'), ('story_published', 'Story Published')], max_length=20),
        ),
    ]
