# Generated by Django 6.0.7 on 2026-08-10 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_verb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('liked_story', 'Liked Story'), ('liked_comment', 'Liked Comment'), ('commented', 'Commented'), ('replied', 'Replied'), ('new_follower', 'New Follower'), ('complete_profile', 'Complete Profile')], max_length=20),
        ),
    ]
