# Generated by Django 6.0.7 on 2026-08-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, default='user/cover/defaultCover.png', upload_to='user/cover/'),
        ),
    ]
