# Generated by Django 6.0.7 on 2026-07-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='user/avatars/default.png', upload_to='user/avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, default='user/cover/defaultCover.jpg', upload_to='user/cover/'),
        ),
    ]
