# Generated by Django 6.0.7 on 2026-08-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_avatar_alter_profile_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(),
        ),
    ]
