# Generated by Django 6.0.7 on 2026-08-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_alter_follow_options_follow_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
    ]
