# Generated by Django 6.0.7 on 2026-07-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_options_story_slug_alter_story_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='auther',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
