# Generated by Django 6.0.7 on 2026-08-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_remove_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=10),
        ),
    ]
